#Multi-configuration and multi-agent job options are not exported to YAML. Configure these options using documentation guidance: https://docs.microsoft.com/vsts/pipelines/process/phases
trigger:
  none

pool:
  name: Ansys
variables:
  python.version: '3.7.7'
  python.venv: 'testvenv'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

- script: |
    python -venv '$(python.venv)'
    '$(python.venv)\Scripts\activate.bat'
    pip install pip -U
    python -c "import sys; print(sys.executable)"
  displayName: 'Create virtual env'

- script: |
    '$(python.venv)\Scripts\activate.bat'
    pip install . --use-feature=in-tree-build
    pip install -r requirements_test.txt
    pip install pytest-azurepipelines
    mkdir tmp
    cd tmp
    python -c "import pyaedt; print('Imported pyaedt')"
  displayName: 'Install pyaedt'

- script: |
    '$(python.venv)\Scripts\activate.bat'
    pip install -r requirements_docs.txt
    doc\make.bat html
  displayName: 'Build documentation'

- task: PublishBuildArtifacts@1
  displayName: 'Publish documentation'
  inputs:
    PathtoPublish: doc/_build/html
    ArtifactName: documentation

