trigger:
  branches:
    include:
    - '*'
    exclude:
    - '*no-ci*'
  tags:
    include:
    - '*'

pool:
  name: Ansys
variables:
  python.version: '3.7.7'
  python.venv: 'testvenv'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

- script: |
    python -venv '$(python.venv)'
    '$(python.venv)\Scripts\activate.bat'
    pip install pip -U
    python -c "import sys; print(sys.executable)"
  displayName: 'Create virtual env'

- script: |
    '$(python.venv)\Scripts\activate.bat'
    pip install . --use-feature=in-tree-build
    pip install -r requirements_test.txt
    pip install pytest-azurepipelines
    mkdir tmp
    cd tmp
    python -c "import pyaedt; print('Imported pyaedt')"
  displayName: 'Install pyaedt'

- script: |
    '$(python.venv)\Scripts\activate.bat'
    pip install -r requirements_docs.txt
    doc\make.bat html
  displayName: 'Build documentation'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: doc/_build/html
    ArtifactName: documentation
  displayName: 'Publish documentation'

- script: |
    set -ex
    git init
    git config --local user.name ""
    git config --local user.email "$(GH_EMAIL)"
    touch .nojekyll
    git add .
    git commit -m "Documentation generated by $(Build.DefinitionName)"
  displayName: "Init git and add docs"
  workingDirectory: doc/_build/html

- script: |
    set -ex
    git config --global --add http.https://pyansys-ci-bot@github.com/pyansys/PyAEDT-docs-dev/_git/.extraHeader "AUTHORIZATION: Basic $(GH_PAT)"
    git remote add origin https://github.com/pyansys/PyAEDT-docs-dev.git
    git push -u origin master
  displayName: "TESTING: Publish GitHub Pages on any commit"
  workingDirectory: doc/_build/html

- script: |
    set -ex
    git config --global --add http.https://pyansys-ci-bot@github.com/pyansys/PyAEDT-docs/_git/.extraHeader "AUTHORIZATION: Basic $(GH_PAT)"
    git remote add origin https://github.com/pyansys/PyAEDT-docs.git
    git push -u origin master
  displayName: "Publish GitHub Pages on Tag"
  condition: contains(variables['Build.SourceBranch'], 'refs/tags/'
  workingDirectory: doc/_build/html
