trigger:
  branches:
    include:
    - '*'
    exclude:
    - '*no-ci*'
  tags:
    include:
    - '*'

pool:
  name: pyansys
variables:
  python.version: '3.8'
  python.venv: 'testvenv'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

- powershell: |
    python -m venv '$(python.venv)'
    .\'$(python.venv)\Scripts\Activate.ps1'
    python -m pip install pip -U
    python -c "import sys; print(sys.executable)"
  displayName: 'Create virtual env'

- powershell: |
    .\'$(python.venv)\Scripts\Activate.ps1'
    python -m pip install . --use-feature=in-tree-build
    python -m pip install -r requirements_test.txt
    python -m pip install pytest-azurepipelines
    mkdir tmp
    cd tmp
    python -c "import pyaedt; print('Imported pyaedt')"
  displayName: 'Install pyaedt'

- powershell: |
    .\'$(python.venv)\Scripts\Activate.ps1'
    python -m pip install -r requirements_docs.txt
  displayName: 'install documentation build requirements'

- powershell: |
    C:doc\make.bat html
  displayName: 'Build documentation'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: doc\_build\html
    ArtifactName: documentation
  displayName: 'Publish documentation'

- powershell: |
    git init
    git config --local user.name "pyansys-ci-bot"
    git config --local user.email "$(GH_EMAIL)"
    git config --local --add http.https://pyansys-ci-bot@github.com/pyansys/PyAEDT-docs-dev/_git/.extraHeader "AUTHORIZATION: Basic $(GH_PAT)"
    New-Item -ItemType file .nojekyll
    git add .
    git commit -m "Documentation generated by $(Build.DefinitionName)"
  displayName: "Init git and add docs"
  workingDirectory: doc/_build/html

- powershell: |
    git remote add origin https://github.com/pyansys/PyAEDT-docs-dev.git
    git push -u origin master
  displayName: "TESTING: Publish GitHub Pages merge commit"
  condition: contains(variables['Build.SourceBranch'], 'refs/heads/main')
  workingDirectory: doc/_build/html

# - script: |
#     set -ex
#     git remote add origin https://github.com/pyansys/PyAEDT-docs.git
#     git push -u origin master
#   displayName: "Publish GitHub Pages on Tag"
#   condition: contains(variables['Build.SourceBranch'], 'refs/tags/')
#   workingDirectory: doc/_build/html
