
trigger:
  branches:
    include:
    - '*'
    exclude:
    - gh-pages
  tags:
    include:
    - '*'

pr:
  branches:
    exclude:
    - '*'

jobs:
- job: DocGalleryBuild
  pool:
    vmImage: 'windows-2019'

  variables:
    python.version: '3.7'
    python.venv: 'docs_venv'
    ANSYSEM_ROOT211: '$(System.DefaultWorkingDirectory)/aedt/Win64'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      git clone --depth 1 https://github.com/pyansys/aedt-req
      cd aedt-req
      install.bat
    displayName: Install Redistributables

  - powershell: |
      python -m pip install pip -U
    displayName: Upgrade pip

  - powershell: |
      pip install . --use-feature=in-tree-build
      mkdir tmp
      cd tmp
      python -c "import pyaedt"
    displayName: Install pyaedt

  - task: UniversalPackages@0
    inputs:
      command: 'download'
      downloadDirectory: '$(System.DefaultWorkingDirectory)/aedt'
      feedsToUse: 'internal'
      vstsFeed: '705e121a-9631-49f5-8aaf-c7142856f923'
      vstsFeedPackage: 'aedt_full'
      vstsPackageVersion: '21.1.0'

  - powershell: |
      ls '$(ANSYSEM_ROOT211)'
    displayName: List AEDT files

  - powershell: |
      Set-StrictMode -Version Latest
      $ErrorActionPreference = "Stop"
      $PSDefaultParameterValues['*:ErrorAction']='Stop'
      git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
      powershell gl-ci-helpers/appveyor/install_opengl.ps1
    displayName: 'Install OpenGL'

  - powershell: |
      $env:ANSYSLMD_LICENSE_FILE = '1055@$(LICENSE_SRV_IP)'
      python -c "import pyaedt;dsk = pyaedt.Desktop();print(dsk);dsk.force_close_desktop()"
    displayName: Verify AEDT install with pyaedt

  - powershell: |
      $env:ANSYSLMD_LICENSE_FILE = '1055@$(LICENSE_SRV_IP)'
      pip install -r requirements_docs.txt
      doc\make.bat html
    displayName: 'Build documentation'
